function [fofu_name, dynamics_name, speed_name] = fofuid_2_runvars(fofu_id)
    fofu_list = [
        "random_1.dat", ...
        "random_2.dat", ...
        "random_3.dat", ...
        "random_4.dat", ...
        "random_5.dat", ...
        "testing_func.dat", ...        
        "testing_func_negative.dat", ...
        "testing_func_mirror.dat", ...
        "testing_func_mirror_negative.dat", ...
        "validation_func.dat", ...
        "validation_func_negative.dat", ...
        "validation_func_mirror.dat", ...
        "validation_func_mirror_negative.dat"];

    dynamics = [
        "", "", "", "", "", ...
        "3", "4", "4", "3", ...
        "3", "4", "4", "3"];

    speed = [
        "", "", "", "", "", ...
        "1", "1", "0", "0", ...
        "1", "1", "0", "0"];
    
    fofu_name = fofu_list(fofu_id);
    dynamics_name = dynamics(fofu_id);
    speed_name = speed(fofu_id);
end

